name: model
description: "Model package"
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  awesome_dio_interceptor: ^1.3.0
  dio: ^5.9.0
  json_annotation: ^4.9.0
  retrofit: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.3
  build_runner: ^2.10.4
  retrofit_generator: 10.2.0

dependency_overrides:
  analyzer: ^8.2.0
