name: gestione_libri_desktop
description: "Deskot app for handle book orders"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pub_semver: ^2.2.0

  model:
    path: model
  view_model:
    path: view_model
  view:
    path: view

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true