name: gestione_libri_desktop
description: "Deskot app for handle book orders"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  adaptive_theme: ^3.7.2
  cupertino_icons: ^1.0.8
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  pub_semver: ^2.2.0
  responsive_framework: ^1.5.1

  model:
    path: model
  view_model:
    path: view_model
  view:
    path: view

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.10.4
  go_router_builder: ^4.1.3

flutter:
  uses-material-design: true

dependency_overrides:
  analyzer: ^8.2.0