name: view
description: "View package"
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  adaptive_theme: ^3.7.2
  material_table_view: ^5.5.2
  responsive_framework: ^1.5.1


  go_router: ^17.0.1


  gap: ^3.0.1
  #intersperse: ^2.0.0
  recase: ^4.1.0

  view_model:
    path: ../view_model

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0

flutter_gen:
  output: lib/src/generated/
  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true
  generate: true